gantt
    title Example Project Roadmap
    dateFormat YYYY-MM-DD
    section Project Planning
        Scope Project and Gather Requirements  :a1, 2030-01-01, 30d
        Model Advisory Board Signoff    : milestone, after a1, 1d
    section Model Development
        Data Acquisition :2030-02-01, 12d
        Model Build    :24d
        Model Validation :21d
        Final Stakeholder Signoff : milestone, 1d
    section Pilot
        In Pilot : 21d
        Model Adjustments : 7d
    section Deployment
        Code Hardening and Unit Testing : 21d
        Application Integration and Testing : 21d
    section Monitoring
        Ongoing Monitoring Report : milestone, 1d