project:
  type: website
  output-dir: ../docs

website:
  title: "Data Science Project Management"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project_planning.qmd
        text: Project Planning
      - href: status_updates.qmd
        text: Status Updates
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



